// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviePages.Data;

#nullable disable

namespace MoviePages.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    partial class MovieDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-rc.1.24451.1");

            modelBuilder.Entity("Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Titanic",
                            Year = 1997
                        },
                        new
                        {
                            Id = 2,
                            Name = "The Shawshank Redemption",
                            Year = 1994
                        },
                        new
                        {
                            Id = 3,
                            Name = "The Godfather",
                            Year = 1972
                        },
                        new
                        {
                            Id = 4,
                            Name = "The Dark Knight",
                            Year = 2008
                        },
                        new
                        {
                            Id = 5,
                            Name = "Pulp Fiction",
                            Year = 1994
                        },
                        new
                        {
                            Id = 6,
                            Name = "Forrest Gump",
                            Year = 1994
                        },
                        new
                        {
                            Id = 7,
                            Name = "Inception",
                            Year = 2010
                        },
                        new
                        {
                            Id = 8,
                            Name = "Fight Club",
                            Year = 1999
                        },
                        new
                        {
                            Id = 9,
                            Name = "The Matrix",
                            Year = 1999
                        },
                        new
                        {
                            Id = 10,
                            Name = "The Lord of the Rings: The Return of the King",
                            Year = 2003
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
